---
title: "Joins"
output: html_notebook
---

```{r}
library(tidyverse)

customers <- tibble(
  customer_ID = c(001, 002, 004, 005, 008, 010), 
  name = c("John Smith", "Jane Adams", "Robert Landry", "Jane Tow", "Raul Tann", "Hilary Joyal"),
  email_address = c("johnsmith@gmail.com", "janea@gmail.com", "rlabdry@hotmail.com", "janet89@aol.com", "paul.tann1@gmail.com", NA),
  shipping_address = c("32 Station Road, Edinburgh", "42 Park Drive, Edinburgh", NA, "10 Gardiner Rd, Edinburgh", "12 Main St, Edinburgh", " 234 Queensferry Rd, Edinburgh,")
)
customers

orders <- tibble(
  customer_ID = c(001, 002, 005, 010, 012, 001), 
  order_number = c("KU65781", "SU98201", "JS76821", "YR28212", "JS91221","YR21873"),
  order_total = c("£32.50", "£56.00", "£100.02", "£20.25", "£39.50", "£45.00"),
  product_code = c("XZY780", "XYZ123", "XYZ256", "XYZ262", "XYZ345", "XYZ127")
)
orders 
```

#inner join

```{r}
inner_join(customers, orders, by = "customer_ID")
```

#left join

```{r}
left_join(customers, orders, by = "customer_ID")
```

```{r}
right_join(customers, orders, by = "customer_ID")
```

# full join

```{r}
full_join(customers, orders, by = "customer_ID")
```

#looking at cases where the key columns have different names

```{r}
customers_adjusted <- rename(customers,
                             this_is_an_identifier = customer_ID)

customers_adjusted
```

#note the "=" in the vector

```{r}
inner_join(customers_adjusted, orders, by = c("this_is_an_identifier" = "customer_ID"))
```

#joining by multiple columns

```{r}
customers2 <- customers %>% 
  mutate(payment_type = c("card", "cash", "cash", "card", "card", "card"))
orders2 <- orders %>%
  mutate(payment_type = c("card", "cash", "cash", "card", "card", "cash"))
```

```{r}
inner_join(customers2, orders2, by = c("customer_ID", "payment_type"))
```

#semi join

```{r}
semi_join(customers, orders, by = "customer_ID")
```

```{r}
inner_join(customers, orders, by = "customer_ID") %>%
  group_by(name) %>% 
  summarise(max = max(order_total))
```

#anti-join

```{r}
anti_join(customers, orders, by = "customer_ID")
```

#binding (sticking on!)

```{r}
statuses <- tibble(
  status = c("active", "active", "inactive", "inactive", "active", "inactive"))
  
bind_cols(customers, statuses)
```

```{r}
past_customers <- tibble(
  custname = c("Dave Brown", "Jess Bishop"),
  customer_ID = c(020, 021),
  email_address = c("dbrown@hotmail.com", "jessb@gmail.com"),
  shipping_address = c("57 Park View, Leith", "12 Reid Way, Broxburn")
)

bind_rows(customers, past_customers)

```

