---
title: "Scales"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```

```{r}
pets <- read_csv("data/pets.csv")
```

```{r}
ggplot(pets) +
  aes(x = age, y = weight, colour = sex) +
  geom_point() +
  scale_x_continuous(breaks = seq(2, 14, by = 2)) +
  scale_y_continuous(breaks = c(5, 7, 9, 11), limits = c(1, 8))
```

```{r}
ggplot(pets) + 
  aes(x = age, y = weight, colour = sex) +
  geom_point() +
  xlim(1, 8)
```

```{r}
ggplot(pets) +
  aes(x = animal, fill = sex) +
  geom_bar()
```

```{r}
ggplot(pets) +
  aes(x = animal, fill = sex) +
  geom_bar() +
  coord_flip()
```

```{r}
ggplot(pets) +
  aes(y = animal, fill = sex) +
  geom_bar()
```

```{r}
monthly_sales <- read_csv("data/monthly_sales.csv")
```

```{r}
monthly_sales %>% 
  mutate(month = factor(month, levels = c("Jan", "Feb", "March", "April"))) %>% 
  ggplot() +
  aes(x = branch, y = sales, fill = month) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::comma) +
  coord_flip()
```

```{r}
monthly_sales %>% 
  mutate(month = factor(month, levels = c("Jan", "Feb", "March", "April"))) %>%
  mutate(sales = sales/1000) %>% 
  ggplot() +
  aes(x = branch, y = sales, fill = month) +
  geom_col(position = "dodge") +
  coord_flip() +
  ylab("Sales/1000")
```